MID = {'Advanced Playmaker (Support)': [['Fir', 'Pas', 'Tec', 'Cmp', 'Dec', 'OTB', 'Tea', 'Vis'],
                                        ['Dri', 'Ant', 'Fla', 'Agi']],
       'Advanced Playmaker (Attack)': [['Dri', 'Fir', 'Pas', 'Tec', 'Cmp', 'Dec', 'OTB', 'Tea', 'Vis'],
                                       ['Ant', 'Fla', 'Agi', 'Acc']],
       'Anchor (Defend)': [['Mar', 'Tck', 'Ant', 'Cnt', 'Dec', 'Pos'],
                           ['Cmp', 'Tea', 'Str']],
       'Attacking Midfielder (Support)': [['Fir', 'Lon', 'Pas', 'Tec', 'Ant', 'Dec', 'Fla', 'OTB'],
                                          ['Dri', 'Cmp', 'Vis', 'Agi']],
       'Attacking Midfielder (Attack)': [['Dri', 'Fir', 'Lon', 'Pas', 'Tec', 'Ant', 'Dec', 'Fla', 'OTB'],
                                         ['Fin', 'Cmp', 'Vis', 'Agi']],
       'Ball Winning Midfielder (Defend)': [['Tck', 'Agg', 'Ant', 'Tea', 'Wor', 'Sta'],
                                            ['Mar', 'Bra', 'Cnt', 'Pos', 'Agi', 'Pac', 'Str']],
       'Ball Winning Midfielder (Support)': [['Tck', 'Agg', 'Ant', 'Tea', 'Wor', 'Sta'],
                                             ['Mar', 'Pas', 'Bra', 'Cnt', 'Agi', 'Pac', 'Str']],
       'Box to Box Midfielder (Support)': [['Pas', 'Tck', 'OTB', 'Tea', 'Wor', 'Sta'],
                                           ['Dri', 'Fin', 'Fir', 'Lon', 'Tec', 'Agg', 'Ant', 'Cmp', 'Dec', 'Pos', 'Acc', 'Bal', 'Pac', 'Str']],
       'Carillero (Support)': [['Fir', 'Pas', 'Tck', 'Dec', 'Pos', 'Tea', 'Sta'],
                               ['Tec', 'Ant', 'Cmp', 'Cnt', 'OTB', 'Vis', 'Wor']],
       'Central Midfielder (Defend)': [['Tck', 'Cnt', 'Dec', 'Pos', 'Tea'],
                                       ['Fir', 'Mar', 'Pas', 'Tec', 'Agg', 'Ant', 'Cmp', 'Wor', 'Sta']],
       'Central Midfielder (Support)': [['Fir', 'Pas', 'Tck', 'Dec', 'Tea'],
                                        ['Tec', 'Ant', 'Cmp', 'Cnt', 'OTB', 'Vis', 'Wor', 'Sta']],
       'Central Midfielder (Attack)': [['Fir', 'Pas', 'Dec', 'OTB'],
                                       ['Lon', 'Tck', 'Tec', 'Ant', 'Cmp', 'Tea', 'Vis', 'Wor', 'Acc', 'Sta']],
       'Deep Lying Playmaker (Defend)': [['Fir', 'Pas', 'Tec', 'Cmp', 'Dec', 'Tea', 'Vis'],
                                         ['Tck', 'Ant', 'Pos', 'Bal']],
       'Deep Lying Playmaker (Support)': [['Fir', 'Pas', 'Tec', 'Cmp', 'Dec', 'Tea', 'Vis'],
                                          ['Ant', 'OTB', 'Pos', 'Bal']],
       'Defensive Midfielder (Defend)': [['Tck', 'Ant', 'Cnt', 'Pos', 'Tea'],
                                         ['Mar', 'Pas', 'Agg', 'Cmp', 'Dec', 'Wor', 'Sta', 'Str']],
       'Defensive Midfielder (Support)': [['Tck', 'Ant', 'Cnt', 'Pos', 'Tea'],
                                          ['Mar', 'Pas', 'Agg', 'Cmp', 'Dec', 'Wor', 'Sta', 'Str']],
       'Enganche (Support)': [['Fir', 'Pas', 'Tec', 'Cmp', 'Dec', 'Vis'],
                              ['Dri', 'Ant', 'Fla', 'OTB', 'Tea', 'Agi']],
       'Half Back (Defend)': [['Mar', 'Tck', 'Ant', 'Cmp', 'Cnt', 'Dec', 'Pos', 'Tea'],
                              ['Fir', 'Pas', 'Agg', 'Bra', 'Wor', 'Jum', 'Sta', 'Str']],
       'Inside Forward (Support)': [['Dri', 'Fir', 'Pas', 'Tec', 'OTB', 'Acc', 'Agi', 'Bal'],
                                    ['Fin', 'Lon', 'Ant', 'Cmp', 'Fla', 'Vis', 'Pac']],
       'Inside Forward (Attack)': [['Dri', 'Fin', 'Fir', 'Tec', 'OTB', 'Acc', 'Agi', 'Bal'],
                                   ['Lon', 'Pas', 'Ant', 'Cmp', 'Fla', 'Pac']],
       'Inverted Winger (Support)': [['Dri', 'Pas', 'Tec', 'OTB', 'Acc'],
                                     ['Cro', 'Fir', 'Lon', 'Cmp', 'Dec', 'Vis', 'Wor', 'Agi', 'Pac', 'Sta']],
       'Inverted Winger (Attack)': [['Dri', 'Pas', 'Tec', 'OTB', 'Acc', 'Agi'],
                                    ['Cro', 'Fir', 'Lon', 'Ant', 'Cmp', 'Dec', 'Fla', 'Vis', 'Pac']],
       'Mezzala (Support)': [['Pas', 'Tec', 'Dec', 'OTB', 'Wor', 'Acc'],
                             ['Dri', 'Fir', 'Lon', 'Tck', 'Ant', 'Cmp' 'Vis', 'Bal', 'Sta']],
       'Mezzala (Attack)': [['Dri', 'Pas', 'Tec', 'Dec', 'OTB', 'Vis', 'Wor', 'Acc'],
                            ['Fin', 'Fir', 'Lon', 'Ant', 'Cmp', 'Fla', 'Bal', 'Sta']],
       'Raumdeuter (Support)': [['Fin', 'Ant', 'Cmp', 'Cnt', 'Dec', 'OTB', 'Bal'],
                                ['Fir', 'Tec', 'Wor', 'Acc', 'Sta']],
       'Regista (Support)': [['Fir', 'Pas', 'Tec', 'Cmp', 'Dec', 'Fla', 'OTB', 'Tea', 'Vis'],
                             ['Dri', 'Lon', 'Ant', 'Bal']],
       'Roaming Playmaker (Support)': [['Fir', 'Pas', 'Tec', 'Ant', 'Cmp', 'Dec', 'OTB', 'Tea', 'Vis', 'Wor', 'Acc', 'Sta'],
                                       ['Dri', 'Lon', 'Cnt', 'Pos', 'Agi', 'Bal', 'Pac']],
       'Segundo Volante (Support)': [['Mar', 'Pas', 'Tck', 'OTB', 'Pos', 'Wor', 'Pac', 'Sta'],
                                     ['Fin', 'Fir', 'Lon', 'Ant', 'Cmp', 'Cnt', 'Dec', 'Acc', 'Bal', 'Str']],
       'Segundo Volante (Attack)': [['Fin', 'Lon', 'Pas', 'Tck', 'Ant', 'OTB', 'Pos', 'Wor', 'Pac', 'Sta'],
                                    ['Fir', 'Mar', 'Cmp', 'Cnt', 'Dec', 'Acc', 'Bal', 'Str']],
       'Shadow Striker (Attack)': [['Dri', 'Fin', 'Fir', 'Ant', 'Cmp', 'OTB', 'Acc'],
                                    ['Pas', 'Tec', 'Cnt', 'Dec', 'Wor', 'Agi', 'Bal', 'Pac', 'Sta']],
       'Wide Midfielder (Defend)': [['Pas', 'Tck', 'Cnt', 'Dec', 'Pos', 'Tea', 'Wor'],
                                    ['Cro', 'Fir', 'Mar', 'Tec', 'Ant', 'Cmp', 'Sta']],
       'Wide Midfielder (Support)': [['Pas', 'Tck', 'Dec', 'Tea', 'Wor', 'Sta'],
                                     ['Cro', 'Fir', 'Tec', 'Ant', 'Cmp', 'Cnt', 'OTB', 'Pos', 'Vis']],
       'Wide Midfielder (Attack)': [['Cro', 'Fir', 'Pas', 'Dec', 'Tea', 'Wor', 'Sta'],
                                    ['Tck', 'Tec', 'Ant', 'Cmp', 'OTB', 'Vis']],
       'Wide Playmaker (Support)': [['Fir', 'Pas', 'Tec', 'Cmp', 'Dec', 'Tea', 'Vis'],
                                    ['Dri', 'OTB', 'Agi']],
       'Wide Playmaker (Attack)': [['Dri', 'Fir', 'Pas', 'Tec', 'Cmp', 'Dec', 'OTB', 'Tea', 'Vis'],
                                   ['Ant', 'Fla', 'Acc', 'Agi']],
       'Wide Target Forward (Support)': [['Head', 'Bra', 'Tea', 'Jum', 'Str'],
                                         ['Cro', 'Fir', 'Ant', 'OTB', 'Wor', 'Bal', 'Sta']],
       'Wide Target Forward (Attack)': [['Head', 'Bra', 'OTB', 'Jum', 'Str'],
                                        ['Cro', 'Fin', 'Fir', 'Ant', 'Tea', 'Wor', 'Bal', 'Sta']],
       'Winger (Support)': [['Cro', 'Dri', 'Tec', 'OTB', 'Acc', 'Pac'],
                            ['Fir', 'Pas', 'Wor', 'Agi', 'Sta']],
       'Winger (Attack)': [['Cro', 'Dri', 'Tec', 'OTB', 'Acc', 'Pac'],
                           ['Fir', 'Pas', 'Ant', 'Fla', 'Agi']]
       }



GK={'Sweeper Keeper(Defend)':
  [[' Ref ', ' Pos ', ' Ant ', ' Cnt ', ' Kic ', ' Agi ', ' Cmd ', ' 1v1 '],
  [' Vis ', ' Cmp ', ' Pas ', ' Dec ', ' Fir ', ' Com ', ' Acc ', ' Aer ', ' Thr ', ' Han ', ' TRO '],
  [' Agg ', ' Jum ', ' Pun ', ' Nat ', ' OtB ', ' Tec ', ' Tea ', ' Fre ', ' Pen ', ' Fla ', ' Ldr ', ' Det ', ' Pac ', ' Str ', ' Ecc ', ' Bal ', ' Sta ', ' Wor ', ' Bra '],
  [' L Th ', ' Lon ', ' Tck ', ' Cro ', ' Mar ', ' Cor ', ' Hea ', ' Dri ', ' Fin ']],

    'Sweeper Keeper(Support)': [[' Cmp ', ' Ref ', ' Pos ', ' Ant ', ' Cnt ', ' Kic ', ' Agi ', ' Cmd ', ' 1v1 ', ' TRO '],
  [' Vis ', ' Pas ', ' Dec ', ' Fir ', ' Com ', ' Acc ', ' Aer ', ' Thr ', ' Han '],
  [' Agg ', ' Jum ', ' Pun ', ' Nat ', ' OtB ', ' Tec ', ' Tea ', ' Fre ', ' Pen ', ' Fla ', ' Ldr ', ' Det ', ' Pac ', ' Str ', ' Ecc ', ' Bal ', ' Sta ', ' Wor ', ' Bra '],
  [' L Th ', ' Lon ', ' Tck ', ' Cro ', ' Mar ', ' Cor ', ' Hea ', ' Dri ', ' Fin ']],

'Sweeper Keeper(Attack)': [[' Cmp ', ' Ref ', ' Pos ', ' Ant ', ' Cnt ', ' Kic ', ' Agi ', ' Cmd ', ' 1v1 ', ' TRO '],
  [' Vis ', ' Pas ', ' Dec ', ' Fir ', ' Com ', ' Acc ', ' Aer ', ' Thr ', ' Han ', ' Ecc '],
  [' Agg ', ' Jum ', ' Pun ', ' Nat ', ' OtB ', ' Tec ', ' Tea ', ' Fre ', ' Pen ', ' Fla ', ' Ldr ', ' Det ', ' Pac ', ' Str ', ' Bal ', ' Sta ', ' Wor ', ' Bra '],
  [' L Th ', ' Lon ', ' Tck ', ' Cro ', ' Mar ', ' Cor ', ' Hea ', ' Dri ', ' Fin ']],


'Goalkeeper (Defend)': [[' Ref ', ' Pos ', ' Cnt ', ' Com ', ' Aer ', ' Han ', ' Kic ', ' Agi ', ' Cmd '],
  [' Ant ', ' Dec ', ' Thr ', ' 1v1 '],
  [' Agg ', ' Jum ', ' Pun ', ' Nat ', ' Vis ', ' OtB ', ' Tec ', ' Tea ', ' Cmp ', ' Fre ', ' Pen ', ' Pas ', ' Fla ', ' Ldr ', ' Det ', ' Fir ', ' Acc ', ' Pac ', ' Str ', ' Ecc ', ' Bal ', ' Sta ', ' Wor ', ' Bra ', ' TRO '],
  [' L Th ', ' Lon ', ' Tck ', ' Cro ', ' Mar ', ' Cor ', ' Hea ', ' Dri ', ' Fin ']]}


FW={'Complete Forward(Attack)': [[' OtB ', ' Tec ', ' Cmp ', ' Ant ', ' Hea ', ' Fir ', ' Acc ', ' Str ', ' Dri ', ' Agi ', ' Fin '],
  [' Jum ', ' Vis ', ' Lon ', ' Tea ', ' Pas ', ' Dec ', ' Pac ', ' Bal ', ' Sta ', ' Wor '],
  [' Agg ', ' Nat ', ' L Th ', ' Tck ', ' Fre ', ' Pos ', ' Pen ', ' Fla ', ' Cro ', ' Mar ', ' Ldr ', ' Cor ', ' Cnt ', ' Det ', ' Bra '],
  [' Pun ', ' Ref ', ' Com ', ' Aer ', ' Thr ', ' Han ', ' Ecc ', ' Kic ', ' Cmd ', ' 1v1 ', ' TRO ']],

'Complete Forward(Support)': [[' Vis ', ' Lon ', ' OtB ', ' Tec ', ' Cmp ', ' Pas ', ' Ant ', ' Dec ', ' Hea ', ' Fir ', ' Acc ', ' Str ', ' Dri ', ' Agi '],
  [' Jum ', ' Tea ', ' Pac ', ' Bal ', ' Sta ', ' Wor ', ' Fin '],
  [' Agg ', ' Nat ', ' L Th ', ' Tck ', ' Fre ', ' Pos ', ' Pen ', ' Fla ', ' Cro ', ' Mar ', ' Ldr ', ' Cor ', ' Cnt ', ' Det ', ' Bra '],
  [' Pun ', ' Ref ', ' Com ', ' Aer ', ' Thr ', ' Han ', ' Ecc ', ' Kic ', ' Cmd ', ' 1v1 ', ' TRO ']],

'Target Forward(Support)': [[' Jum ', ' Tea ', ' Hea ', ' Str ', ' Bal ', ' Bra '],
  [' Agg ', ' OtB ', ' Cmp ', ' Ant ', ' Dec ', ' Fir ', ' Fin '],
  [' Nat ', ' Vis ', ' L Th ', ' Lon ', ' Tck ', ' Tec ', ' Fre ', ' Pos ', ' Pen ', ' Pas ', ' Fla ', ' Cro ', ' Mar ', ' Ldr ', ' Cor ', ' Cnt ', ' Det ', ' Acc ', ' Pac ', ' Dri ', ' Sta ', ' Agi ', ' Wor '],
  [' Pun ', ' Ref ', ' Com ', ' Aer ', ' Thr ', ' Han ', ' Ecc ', ' Kic ', ' Cmd ', ' 1v1 ', ' TRO ']],

'Target Forward(Attack)': [[' Jum ', ' OtB ', ' Cmp ', ' Hea ', ' Str ', ' Bal ', ' Bra ', ' Fin '],
  [' Agg ', ' Tea ', ' Ant ', ' Dec ', ' Fir '],
  [' Nat ', ' Vis ', ' L Th ', ' Lon ', ' Tck ', ' Tec ', ' Fre ', ' Pos ', ' Pen ', ' Pas ', ' Fla ', ' Cro ', ' Mar ', ' Ldr ', ' Cor ', ' Cnt ', ' Det ', ' Acc ', ' Pac ', ' Dri ', ' Sta ', ' Agi ', ' Wor '],
  [' Pun ', ' Ref ', ' Com ', ' Aer ', ' Thr ', ' Han ', ' Ecc ', ' Kic ', ' Cmd ', ' 1v1 ', ' TRO ']],

'Pressing Forward(Defend)': [[' Agg ', ' Tea ', ' Ant ', ' Dec ', ' Acc ', ' Pac ', ' Sta ', ' Wor ', ' Bra '],
  [' Cmp ', ' Cnt ', ' Fir ', ' Str ', ' Bal ', ' Agi '],
  [' Jum ', ' Nat ', ' Vis ', ' L Th ', ' Lon ', ' OtB ', ' Tck ', ' Tec ', ' Fre ', ' Pos ', ' Pen ', ' Pas ', ' Fla ', ' Cro ', ' Mar ', ' Ldr ', ' Cor ', ' Det ', ' Hea ', ' Dri ', ' Fin '],
  [' Pun ', ' Ref ', ' Com ', ' Aer ', ' Thr ', ' Han ', ' Ecc ', ' Kic ', ' Cmd ', ' 1v1 ', ' TRO ']],

'Pressing Forward(Support)': [[' Agg ', ' Tea ', ' Ant ', ' Dec ', ' Acc ', ' Pac ', ' Sta ', ' Wor ', ' Bra '],
  [' OtB ', ' Cmp ', ' Pas ', ' Cnt ', ' Fir ', ' Str ', ' Bal ', ' Agi '],
  [' Jum ', ' Nat ', ' Vis ', ' L Th ', ' Lon ', ' Tck ', ' Tec ', ' Fre ', ' Pos ', ' Pen ', ' Fla ', ' Cro ', ' Mar ', ' Ldr ', ' Cor ', ' Det ', ' Hea ', ' Dri ', ' Fin '],
  [' Pun ', ' Ref ', ' Com ', ' Aer ', ' Thr ', ' Han ', ' Ecc ', ' Kic ', ' Cmd ', ' 1v1 ', ' TRO ']],

'Pressing Forward(Attack)': [[' Agg ', ' OtB ', ' Tea ', ' Ant ', ' Acc ', ' Pac ', ' Sta ', ' Wor ', ' Bra '],
  [' Cmp ', ' Cnt ', ' Dec ', ' Fir ', ' Str ', ' Bal ', ' Agi ', ' Fin '],
  [' Jum ', ' Nat ', ' Vis ', ' L Th ', ' Lon ', ' Tck ', ' Tec ', ' Fre ', ' Pos ', ' Pen ', ' Pas ', ' Fla ', ' Cro ', ' Mar ', ' Ldr ', ' Cor ', ' Det ', ' Hea ', ' Dri '],
  [' Pun ', ' Ref ', ' Com ', ' Aer ', ' Thr ', ' Han ', ' Ecc ', ' Kic ', ' Cmd ', ' 1v1 ', ' TRO ']],

'Deep Lying Forward(Support)': [[' OtB ', ' Tec ', ' Tea ', ' Cmp ', ' Pas ', ' Dec ', ' Fir '],
  [' Vis ', ' Fla ', ' Ant ', ' Str ', ' Bal ', ' Fin '],
  [' Agg ', ' Jum ', ' Nat ', ' L Th ', ' Lon ', ' Tck ', ' Fre ', ' Pos ', ' Pen ', ' Cro ', ' Mar ', ' Ldr ', ' Cor ', ' Cnt ', ' Det ', ' Hea ', ' Acc ', ' Pac ', ' Dri ', ' Sta ', ' Agi ', ' Wor ', ' Bra '],
  [' Pun ', ' Ref ', ' Com ', ' Aer ', ' Thr ', ' Han ', ' Ecc ', ' Kic ', ' Cmd ', ' 1v1 ', ' TRO ']],

'Deep Lying Forward(Attack)': [[' OtB ', ' Tec ', ' Tea ', ' Cmp ', ' Pas ', ' Dec ', ' Fir '],
    [' Vis ', ' Fla ', ' Ant ', ' Str ', ' Dri ', ' Bal ', ' Fin '],
    [' Agg ', ' Jum ', ' Nat ', ' L Th ', ' Lon ', ' Tck ', ' Fre ', ' Pos ', ' Pen ', ' Cro ', ' Mar ', ' Ldr ', ' Cor ', ' Cnt ', ' Det ', ' Hea ', ' Acc ', ' Pac ', ' Sta ', ' Agi ', ' Wor ', ' Bra '],
    [' Pun ', ' Ref ', ' Com ', ' Aer ', ' Thr ', ' Han ', ' Ecc ', ' Kic ', ' Cmd ', ' 1v1 ', ' TRO ']],

'Poacher(Attack)': [[' OtB ', ' Cmp ', ' Ant ', ' Fin '],
  [' Tec ', ' Dec ', ' Hea ', ' Fir ', ' Acc '],
  [' Agg ', ' Jum ', ' Nat ', ' Vis ', ' L Th ', ' Lon ', ' Tck ', ' Tea ', ' Fre ', ' Pos ', ' Pen ', ' Pas ', ' Fla ', ' Cro ', ' Mar ', ' Ldr ', ' Cor ', ' Cnt ', ' Det ', ' Pac ', ' Str ', ' Dri ', ' Bal ', ' Sta ', ' Agi ', ' Wor ', ' Bra '],
  [' Pun ', ' Ref ', ' Com ', ' Aer ', ' Thr ', ' Han ', ' Ecc ', ' Kic ', ' Cmd ', ' 1v1 ', ' TRO ']],

'Advanced Forward(Attack)': [[' OtB ', ' Tec ', ' Cmp ', ' Fir ', ' Acc ', ' Dri ', ' Fin '],
  [' Pas ', ' Ant ', ' Dec ', ' Pac ', ' Bal ', ' Sta ', ' Agi ', ' Wor '],
  [' Agg ', ' Jum ', ' Nat ', ' Vis ', ' L Th ', ' Lon ', ' Tck ', ' Tea ', ' Fre ', ' Pos ', ' Pen ', ' Fla ', ' Cro ', ' Mar ', ' Ldr ', ' Cor ', ' Cnt ', ' Det ', ' Hea ', ' Str ', ' Bra '],
  [' Pun ', ' Ref ', ' Com ', ' Aer ', ' Thr ', ' Han ', ' Ecc ', ' Kic ', ' Cmd ', ' 1v1 ', ' TRO ']],

'Trequartista(Attack)': [[' Vis ', ' OtB ', ' Tec ', ' Cmp ', ' Pas ', ' Fla ', ' Dec ', ' Fir ', ' Acc ', ' Dri '],
  [' Ant ', ' Bal ', ' Agi ', ' Fin '],
 [' Agg ', ' Jum ', ' Nat ', ' L Th ', ' Lon ', ' Tck ', ' Tea ', ' Fre ', ' Pos ', ' Pen ', ' Cro ', ' Mar ', ' Ldr ', ' Cor ', ' Cnt ', ' Det ', ' Hea ', ' Pac ', ' Str ', ' Sta ', ' Wor ', ' Bra '],
  [' Pun ', ' Ref ', ' Com ', ' Aer ', ' Thr ', ' Han ', ' Ecc ', ' Kic ', ' Cmd ', ' 1v1 ', ' TRO ']],

'False Nine(Support)': [[' Vis ', ' OtB ', ' Tec ', ' Cmp ', ' Pas ', ' Dec ', ' Fir ', ' Acc ', ' Dri ', ' Agi '],
  [' Tea ', ' Fla ', ' Ant ', ' Bal ', ' Fin '],
  [' Agg ', ' Jum ', ' Nat ', ' L Th ', ' Lon ', ' Tck ', ' Fre ', ' Pos ', ' Pen ', ' Cro ', ' Mar ', ' Ldr ', ' Cor ', ' Cnt ', ' Det ', ' Hea ', ' Pac ', ' Str ', ' Sta ', ' Wor ', ' Bra '],
  [' Pun ', ' Ref ', ' Com ', ' Aer ', ' Thr ', ' Han ', ' Ecc ', ' Kic ', ' Cmd ', ' 1v1 ', ' TRO ']]

}



DEF = {"Ball Playing Defender(Defender)": [[" Jum ", " Tck ", " Cmp ", " Pos ", " Pas ", " Mar ", " Hea ", " Str "],
                                           [" Agg ", " Vis ", " Tec ", " Ant ", " Cnt ", " Dec ", " Fir ", " Pac ", " Bra "]],
       "Ball Playing Defender(Stopper)": [[" Agg ", " Jum ", " Tck ", " Cmp ", " Pos ", " Pas ", " Dec ", " Hea ", " Str ", " Bra "],
                                          [" Vis ", " Tec ", " Ant ", " Mar ", " Cnt ", " Fir "]],
       "Ball Playing Defender(Cover)": [[" Tck ", " Cmp ", " Pos ", " Pas ", " Ant ", " Mar ", " Cnt ", " Dec ", " Pac "],
                                        [" Jum ", " Vis ", " Tec ", " Hea ", " Fir ", " Str ", " Bra "]],

       "No-Nonsense Centre-Back(Defend)": [[" Jum ", " Tck ", " Pos ", " Mar ", " Hea ", " Str "],
                                           [" Agg ", " Ant ", " Cnt ", " Pac ", " Bra "]],
       "No-Nonsense Centre-Back(Stopper)": [[" Agg ", " Jum ", " Tck ", " Pos ", " Hea ", " Str ", " Bra "],
                                            [" Ant ", " Mar ", " Cnt "]],
       "No-Nonsense Centre-Back(Cover)": [[" Tck ", " Pos ", " Ant ", " Mar ", " Cnt ", " Pac "],
                                          [" Jum ", " Hea ", " Str ", " Bra "]],

       "Wide Center-Back(Defend)": [[" Jum ", " Tck ", " Pos ", " Cro ", " Mar ", " Hea ", " Str ", " Sta "],
                                    [" Agg ", " Cmp ", " Ant ", " Cnt ", " Dec ", " Pac ", " Dri ", " Wor ", " Bra "]],
       "Wide Center-Back(Support)": [[' Jum ', ' Tck ', ' Pos ', ' Cro ', ' Mar ', ' Hea ', ' Pac ', ' Str ', ' Dri ', ' Sta '],
                                     [' Agg ', ' OtB ', ' Cmp ', ' Ant ', ' Cnt ', ' Dec ', ' Wor ', ' Bra ']],
       "Wide Center-Back(Attack)": [[' Jum ', ' OtB ', ' Tck ', ' Cro ', ' Mar ', ' Hea ', ' Pac ', ' Str ', ' Dri ', ' Sta '],
                                    [' Agg ', ' Cmp ', ' Pos ', ' Ant ', ' Cnt ', ' Dec ', ' Wor ', ' Bra ']],

       "Libero(Support)": [[' Vis ', ' Tck ', ' Tea ', ' Cmp ', ' Pos ', ' Pas ', ' Ant ', ' Mar ', ' Cnt ', ' Dec ', ' Fir ', ' Pac '],
                           [' Jum ', ' Tec ', ' Fla ', ' Hea ', ' Str ', ' Dri ', ' Bal ', ' Sta ', ' Agi ', ' Bra ']],
       "Libero(Attack)": [[' Vis ', ' Tck ', ' Tea ', ' Cmp ', ' Pos ', ' Pas ', ' Fla ', ' Ant ', ' Mar ', ' Cnt ', ' Dec ', ' Fir ', ' Pac ', ' Dri '],
                          [' Jum ', ' Lon ', ' Tec ', ' Hea ', ' Acc ', ' Str ', ' Bal ', ' Sta ', ' Agi ', ' Bra ']],

       "Central Defender(Defend)": [[' Jum ', ' Tck ', ' Pos ', ' Mar ', ' Hea ', ' Str '],
                                    [' Agg ', ' Cmp ', ' Ant ', ' Cnt ', ' Dec ', ' Pac ', ' Bra ']],
       "Central Defender(Stopper)": [[' Agg ', ' Jum ', ' Tck ', ' Pos ', ' Dec ', ' Hea ', ' Str ', ' Bra '],
                                     [' Cmp ', ' Ant ', ' Mar ', ' Cnt ']],
       "Central Defender(Cover)": [[' Tck ', ' Pos ', ' Ant ', ' Mar ', ' Cnt ', ' Dec ', ' Pac '],
                                   [' Jum ', ' Cmp ', ' Hea ', ' Str ', ' Bra ']],

       "Full-Back(Defend)": [[' Tck ', ' Pos ', ' Ant ', ' Mar ', ' Cnt '],
                             [' Tea ', ' Cmp ', ' Pas ', ' Cro ', ' Dec ', ' Pac ', ' Sta ']],
       "Full-Back(Support)": [[' Tck ', ' Tea ', ' Pos ', ' Ant ', ' Mar ', ' Cnt ', ' Wor '],
                              [' Tec ', ' Cmp ', ' Pas ', ' Cro ', ' Dec ', ' Pac ', ' Dri ', ' Sta ']],
       "Full-Back(Attack)": [[' Tck ', ' Tea ', ' Pos ', ' Ant ', ' Cro ', ' Pac ', ' Sta ', ' Wor '],
                             [' OtB ', ' Tec ', ' Cmp ', ' Pas ', ' Mar ', ' Cnt ', ' Dec ', ' Fir ', ' Acc ', ' Dri ',
                              ' Agi ']],
       "Full-Back(Automatic)": [[' Tck ', ' Tea ', ' Pos ', ' Ant ', ' Mar ', ' Cnt ', ' Wor '],
                                [' Tec ', ' Cmp ', ' Pas ', ' Cro ', ' Dec ', ' Pac ', ' Dri ', ' Sta ']],

       "Wing-Back(Defend)": [[' Tck ', ' Tea ', ' Pos ', ' Ant ', ' Mar ', ' Acc ', ' Sta ', ' Wor '],
                             [' OtB ', ' Tec ', ' Pas ', ' Cro ', ' Cnt ', ' Dec ', ' Fir ', ' Pac ', ' Dri ',
                              ' Agi ']],
       "Wing-Back(Support)": [[' OtB ', ' Tck ', ' Tea ', ' Cro ', ' Mar ', ' Acc ', ' Dri ', ' Sta ', ' Wor '],
                              [' Tec ', ' Pos ', ' Pas ', ' Ant ', ' Cnt ', ' Dec ', ' Fir ', ' Pac ', ' Agi ']],
       "Wing-Back(Attack)": [[' OtB ', ' Tck ', ' Tec ', ' Tea ', ' Cro ', ' Acc ', ' Pac ', ' Dri ', ' Sta ', ' Wor '],
                             [' Pos ', ' Pas ', ' Fla ', ' Ant ', ' Mar ', ' Cnt ', ' Dec ', ' Fir ', ' Agi ']],
       "Wing-Back(Automatic)": [[' OtB ', ' Tck ', ' Tea ', ' Cro ', ' Mar ', ' Acc ', ' Dri ', ' Sta ', ' Wor '],
                                [' Tec ', ' Pos ', ' Pas ', ' Ant ', ' Cnt ', ' Dec ', ' Fir ', ' Pac ', ' Agi ']],

       "No-Nonsense Full-Back(Defend)": [[' Tck ', ' Pos ', ' Ant ', ' Mar ', ' Cnt ', ' Str '],
                                         [' Agg ', ' Tea ', ' Hea ', ' Bra ']],

       "Complete Wing-Back(Support)": [[' OtB ', ' Tec ', ' Tea ', ' Pas ', ' Cro ', ' Dec ', ' Fir ', ' Acc ', ' Pac ', ' Dri ', ' Sta ', ' Wor '],
                                       [' Tck ', ' Cmp ', ' Fla ', ' Ant ', ' Bal ', ' Agi ']],
       "Complete Wing-Back(Attack)": [[' OtB ', ' Tec ', ' Tea ', ' Pas ', ' Fla ', ' Cro ', ' Dec ', ' Fir ', ' Acc ', ' Pac ', ' Dri ', ' Sta ',' Wor '],
                                      [' Tck ', ' Cmp ', ' Ant ', ' Bal ', ' Agi ']],

       "Inverted Wing-Back(Defend)": [[' Tck ', ' Tea ', ' Pos ', ' Pas ', ' Ant ', ' Mar ', ' Dec ', ' Wor '],
                                      [' OtB ', ' Tec ', ' Cnt ', ' Fir ', ' Acc ', ' Dri ', ' Sta ', ' Agi ']],
       "Inverted Wing-Back(Support)": [[' OtB ', ' Tck ', ' Tea ', ' Pas ', ' Mar ', ' Dec ', ' Sta ', ' Wor '],
                                       [' Tec ', ' Cmp ', ' Pos ', ' Ant ', ' Cnt ', ' Fir ', ' Acc ', ' Dri ',
                                        ' Agi ']],
       "Inverted Wing-Back(Attack)": [[' OtB ', ' Tck ', ' Tec ', ' Tea ', ' Pas ', ' Mar ', ' Dec ', ' Acc ', ' Dri ', ' Sta ', ' Wor '],
                                      [' Lon ', ' Cmp ', ' Pos ', ' Fla ', ' Ant ', ' Cnt ', ' Fir ', ' Pac ', ' Agi ']],
       "Inverted Wing-Back(Automatic)": [[' OtB ', ' Tck ', ' Tea ', ' Pas ', ' Mar ', ' Dec ', ' Sta ', ' Wor '],
                                         [' Tec ', ' Cmp ', ' Pos ', ' Ant ', ' Cnt ', ' Fir ', ' Acc ', ' Dri ', ' Agi ']]
       }